version: "3"

services:

  nbxplorer:
    restart: unless-stopped
    image: andyjh122/nbxplorer:2.1.14
    expose:
      - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
    volumes:
      - "nbxplorer_datadir:/datadir"

volumes:
    nbxplorer_datadir:
